"""
app.py  –  CrisisRoom FastAPI server
Generated by: openenv init CrisisRoom (adapted)

All environment logic lives in CrisisRoom_environment.py.
This file wires it to the OpenEnv-expected HTTP interface.
"""

from __future__ import annotations

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware

# ── Import env from the openenv-init generated file ───────────────────────────
from server.CrisisRoom_environment import (
    CrisisRoomEnv,
    ALL_SCENARIOS,
    SERVICES,
)

# ── Import schemas from models.py (openenv-init convention) ──────────────────
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from models import (
    ResetRequest,
    StepRequest,
    ObservationResponse,
    StepResponse,
    StateResponse,
    ActionSpaceResponse,
    ObservationSpaceResponse,
    HealthResponse,
    ScenarioInfo,
    ScenariosResponse,
)

# ── App ───────────────────────────────────────────────────────────────────────

app = FastAPI(
    title="CrisisRoom – SRE Incident Response RL Environment",
    description=(
        "OpenEnv-compliant RL environment for the Meta PyTorch OpenEnv Hackathon.\n"
        "Theme 3.1 – World Modeling: Professional Tasks.\n\n"
        "The agent acts as an on-call SRE diagnosing partially-observable production "
        "incidents through tool calls, causal reasoning, and targeted remediation."
    ),
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# ── Global env instance ───────────────────────────────────────────────────────
_env: CrisisRoomEnv = CrisisRoomEnv(max_steps=12, red_herring_prob=0.30)
_episode_active: bool = False


# ── Routes ────────────────────────────────────────────────────────────────────

@app.get("/health", response_model=HealthResponse, tags=["Meta"])
async def health():
    return HealthResponse()


@app.get("/observation_space", response_model=ObservationSpaceResponse, tags=["Environment"])
async def observation_space():
    return ObservationSpaceResponse(**_env.observation_space())


@app.get("/action_space", response_model=ActionSpaceResponse, tags=["Environment"])
async def action_space():
    return ActionSpaceResponse(**_env.action_space())


@app.get("/scenarios", response_model=ScenariosResponse, tags=["Environment"])
async def list_scenarios():
    items = [
        ScenarioInfo(
            name=s.name, description=s.description, root_cause=s.root_cause,
            correct_fix=s.correct_fix, causal_chain=s.causal_chain, hint=s.hint,
        )
        for s in ALL_SCENARIOS
    ]
    return ScenariosResponse(scenarios=items, total=len(items))


@app.post("/reset", response_model=ObservationResponse, tags=["Environment"])
async def reset(request: ResetRequest = ResetRequest()):
    global _env, _episode_active
    _env = CrisisRoomEnv(
        max_steps=12,
        red_herring_prob=0.30,
        curriculum_hint=request.curriculum_hint,
        seed=request.seed,
    )
    obs = _env.reset(scenario_name=request.scenario_name)
    _episode_active = True
    return ObservationResponse(**obs)


@app.post("/step", response_model=StepResponse, tags=["Environment"])
async def step(request: StepRequest):
    global _episode_active
    if not _episode_active:
        raise HTTPException(status_code=400, detail="No active episode. Call POST /reset first.")
    try:
        obs_dict, reward, done, info = _env.step(request.action)
    except RuntimeError as e:
        raise HTTPException(status_code=400, detail=str(e))
    if done:
        _episode_active = False
    return StepResponse(observation=ObservationResponse(**obs_dict), reward=reward, done=done, info=info)


@app.get("/state", response_model=StateResponse, tags=["Debug"])
async def get_state():
    raw = _env.state()
    if raw.get("status") == "not_started":
        return StateResponse(status="not_started")
    return StateResponse(
        scenario_name=raw.get("scenario_name"),
        step_count=raw.get("step_count", 0),
        max_steps=raw.get("max_steps", 12),
        done=raw.get("done", False),
        timed_out=raw.get("timed_out", False),
        diagnosis_made=raw.get("diagnosis_made", False),
        resolution_attempted=raw.get("resolution_attempted", False),
        components_checked=raw.get("components_checked", []),
        status="active" if not raw.get("done") else "done",
    )


# ── Dev entry ─────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=7860, reload=False)